import 'package:flutter/material.dart';

var responseArrayGetWareHouseJourneyMapData;
var responseArrayGetWareHouseJourneyMapDataMsg;

var journeyMapWareHouseImagesList;
var journeyMapWareHouseUserNameList;
var journeyMapWareHouseIdsList;

var responseArrayGetWareHouseJourneyMapDataMapIdWise;
var responseArrayGetWareHouseJourneyMapDataMapIdWiseMsg;

var journeyMapWareHouseImagesMapIdWiseList;
var journeyMapWareHouseUserNameMapIdWiseList;
var journeyMapWareHouseIdsMapIdWiseList;

var journeyMapWareHouseTouchPointsList;
var journeyMapWareHouseCustomerThoughtsList;
var journeyMapWareHouseCustomerExperiencesList;
var journeyMapWareHousePainPointsList;

var selectedWareHouseMapId;